name: "conv-vae-256"
# information about the training task
output_size: 6

# information about the regressor
encoding_size: 256  # should be the same as the encoding
regressor_hidden_size_1: 64
regressor_hidden_size_2: 64
loss: "MSE"

# The number of epochs the MLP is supposed to be trained
# epochs: 1000
batch_size: 32


# information about the sp specified by the exp/run
sensor_processing: 'ConvVaeSensorProcessing'
sp_experiment: 'sensorprocessing_conv_vae'
sp_run: 'proprio_256'

# the training data: use the default
