batch_size: 32
class: ResNetProprioTunedSensorProcessing
epochs: 10
freeze_feature_extractor: true
image_size:
- 256
- 256
latent_size: 256
learning_rate: 0.001
loss: MSELoss
model: ResNetProprioTunedRegression
output_size: 6
proprio_step_1: 64
proprio_step_2: 16
reductor_step_1: 512
training_data:
- - random-both-cameras-video
  - sp_training_00000
  - dev2
- - random-both-cameras-video
  - sp_training_00001
  - dev2
- - random-both-cameras-video
  - sp_training_00002
  - dev2
- - random-both-cameras-video
  - sp_training_00003
  - dev2
validation_data:
- - random-both-cameras-video
  - sp_validation_00000
  - dev2
- - random-both-cameras-video
  - sp_validation_00001
  - dev2
