batch_size: 32
class: VGG19ProprioTunedSensorProcessing
epochs: 10
image_size:
- 256
- 256
latent_size: 256
learning_rate: 0.001
loss: MSELoss
model: VGG19ProprioTunedRegression
output_size: 6
training_data:
- - random-both-cameras-video
  - sp_training_00000
  - dev2
- - random-both-cameras-video
  - sp_training_00001
  - dev2
- - random-both-cameras-video
  - sp_training_00002
  - dev2
- - random-both-cameras-video
  - sp_training_00003
  - dev2
validation_data:
- - random-both-cameras-video
  - sp_validation_00000
  - dev2
- - random-both-cameras-video
  - sp_validation_00001
  - dev2
