class: "VGG19ProprioTunedSensorProcessing"
name : 'vgg19-256'

# image_size: [64, 64]
image_size: [256, 256]
latent_size: 256

model: 'VGG19ProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 10
learning_rate: 0.001
batch_size: 32
output_size: 6

freeze_feature_extractor: True

# the training data in the demonstration / subrun / camera form
# training_data:
#   - ["freeform", "2024_12_26__16_40_20", "dev2"]
#   - ["freeform", "2024_12_26__16_44_06", "dev2"]

# # the testing data in the demonstration / subrun / camera form
# testing_data:
#   - ["freeform", "2024_12_26__16_40_20", "dev2"]


# training_data:
#  - ["random-both-cameras-video", "2025_03_08__14_15_53" , "dev2"]
#  - ["random-both-cameras-video", "2025_03_08__14_16_57" , "dev2"]
#  - ["random-both-cameras-video", "2025_03_08__14_19_12" , "dev2"]
#  - ["random-both-cameras-video", "2025_03_08__14_21_28" , "dev2"]


# the validation data in the demonstration / subrun form
# validation_data:
#   - ["random-both-cameras-video", "2025_03_08__14_23_19" , "dev2"]
#   - ["random-both-cameras-video", "2025_03_08__14_24_52" , "dev2"]

training_data:
 - ["random-both-cameras-video", "2025_03_08__14_15_53" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_16_57" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_19_12" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_21_28" , "dev2"]

# the validation data in the demonstration / subrun form
validation_data:
  - ["random-both-cameras-video", "2025_03_08__14_23_19" , "dev2"]
  - ["random-both-cameras-video", "2025_03_08__14_24_52" , "dev2"]
