batch_size: 64
encoding_size: 128
epochs: 1000
loss: MSE
name: vp_resnet50_128_0001
output_size: 6
regressor_hidden_size_1: 64
sensor_processing: ResNetProprioTunedSensorProcessing
sp_experiment: sensorprocessing_propriotuned_cnn
sp_run: sp_resnet50_128_0001
training_data:
- - random-both-cameras-video
  - vp_training_00000
  - dev2
- - random-both-cameras-video
  - vp_training_00001
  - dev2
- - random-both-cameras-video
  - vp_training_00002
  - dev2
- - random-both-cameras-video
  - vp_training_00003
  - dev2
validation_data:
- - random-both-cameras-video
  - vp_validation_00000
  - dev2
- - random-both-cameras-video
  - vp_validation_00001
  - dev2
