class: "ResNetProprioTunedSensorProcessing"
# resnet-50 00
name : 'resnet-50-256'

# image_size: [64, 64]
image_size: [256, 256]

latent_size: 256

reductor_step_1: 512
proprio_step_1: 64
proprio_step_2: 16
output_size: 6

model: 'ResNetProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 100
learning_rate: 0.002
batch_size: 32
# batch_size: 1

freeze_feature_extractor: True

training_data:
 - ["random-both-cameras-video", "2025_03_08__14_15_53" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_16_57" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_19_12" , "dev2"]
 - ["random-both-cameras-video", "2025_03_08__14_21_28" , "dev2"]


# the validation data in the demonstration / subrun form
validation_data:
  - ["random-both-cameras-video", "2025_03_08__14_23_19" , "dev2"]
  - ["random-both-cameras-video", "2025_03_08__14_24_52" , "dev2"]


